Add database
GretaSovizkaya/java-filmorate pull request #4
Opened 2024-09-19 22:16 UTC by GretaSovizkaya

2024-09-20 19:25 UTC, andrew-larkin requested changes
Привет! Хорошая работа! по бизнес-логике почти нет замечаний, нужно немного поправить контроллеры. А также вернуть тесты, и дописать новые.

2024-09-20 19:25 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> -
не, тесты не надо удалять, желательно еще новые добавить)

2024-09-20 19:25 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmDbController.java
> +    @GetMapping("/genres")
методы связанные с жанрами перенести в соответствующий контроллер

2024-09-20 19:25 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    public Genre findUser(@PathVariable long id) {
findGenre

2024-09-20 19:25 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/RatingController.java
> +    public Rating findUser(@PathVariable int id) {
findMpa

2024-09-20 19:25 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmDbController.java
> +    @GetMapping("/mpa/{id}")
этот метод можно перенести в RatingController

2024-09-21 19:28 UTC, GretaSovizkaya commented
Доброго времени суток) Не совсем поняла, что случилось с веткой (почему не собралась?), тесты добавила в коммите "second try ro pass Task 12")  Надеюсь, сейчас все будет хорошо)

2024-11-10 07:53 UTC, closed without merging